services:
  php:
    build:
      dockerfile: docker-config/php/Dockerfile
    volumes:
      - './public:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './public:/var/www/html'
      - './docker-config/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker-config/database/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 7070:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
